import { Norm } from './types';

// Стартовая база норм из бэкапа клинициста (Степан, июль 2026): «Методичка
// Бехтерева» и нормы Шульте / «10 слов». Валидированы автором. Баллы качества
// пересчитываются при досеве по актуальной схеме — здесь их не фиксируем.
// normId сохранены из исходной базы, чтобы досев был идемпотентным.
const SEED = 'seed';

function seedNorm(n: Partial<Norm> & Pick<Norm, 'normId' | 'sourceRef' | 'methodId' | 'metric' | 'ageMin' | 'ageMax' | 'cellN' | 'statForm' | 'higherIsWorse'>): Norm {
  return {
    version: 1,
    sourceType: 'methodical_guide',
    enteredBy: SEED,
    enteredAt: '2026-07-07T00:00:00.000Z',
    validatedBy: SEED,
    validatedAt: '2026-07-07T00:00:00.000Z',
    validationStatus: 'validated',
    procedureMatch: 'full',
    educationLevel: 'not_stratified',
    language: 'ru',
    clinicalStatus: 'healthy',
    isSkewed: false,
    stratifiedBy: ['age'],
    flags: [],
    active: true,
    appliedCount: 0,
    ...n,
  };
}

export const SEED_NORMS: Norm[] = [
  seedNorm({
    normId: 'norm_seed_ct_iu',
    sourceRef: 'Методичка Бехтерева',
    methodId: 'correction_test',
    metric: 'IU',
    ageMin: 18,
    ageMax: 45,
    cellN: 250,
    statForm: 'cutoff',
    mean: 1,
    sd: 0.05,
    higherIsWorse: true,
    dataCollectionYear: 2015,
    publicationYear: 2015,
  }),
  seedNorm({
    normId: 'norm_seed_ct_errors',
    sourceRef: 'Методичка Бехтерева',
    methodId: 'correction_test',
    metric: 'errors_total',
    ageMin: 18,
    ageMax: 45,
    cellN: 150,
    statForm: 'cutoff',
    mean: 1,
    sd: 1,
    higherIsWorse: true,
  }),
  seedNorm({
    normId: 'norm_seed_schulte_er',
    sourceRef: 'Эффективность работы — Шульте',
    methodId: 'schulte',
    metric: 'ER',
    ageMin: 18,
    ageMax: 45,
    cellN: 200,
    statForm: 'mean_sd',
    mean: 35,
    sd: 4,
    higherIsWorse: false,
  }),
  seedNorm({
    normId: 'norm_seed_schulte_pu',
    sourceRef: 'Психическая устойчивость — Шульте',
    methodId: 'schulte',
    metric: 'PU',
    ageMin: 18,
    ageMax: 45,
    cellN: 148,
    statForm: 'cutoff',
    mean: 1,
    sd: 0.2,
    higherIsWorse: true,
    dataCollectionYear: 2015,
    publicationYear: 2015,
  }),
  seedNorm({
    normId: 'norm_seed_schulte_vr',
    sourceRef: 'Врабатываемость — Шульте',
    methodId: 'schulte',
    metric: 'VR',
    ageMin: 18,
    ageMax: 42,
    cellN: 150,
    statForm: 'cutoff',
    mean: 1,
    sd: 0.2,
    higherIsWorse: true,
    dataCollectionYear: 2015,
    publicationYear: 2015,
  }),
  seedNorm({
    normId: 'norm_seed_tenwords_delayed',
    sourceRef: 'Отсроченное воспроизведение — 10 слов',
    methodId: 'ten_words',
    metric: 'delayed',
    ageMin: 18,
    ageMax: 45,
    cellN: 299,
    statForm: 'mean_sd',
    mean: 8,
    sd: 1.5,
    higherIsWorse: false,
    dataCollectionYear: 2015,
    publicationYear: 2013,
  }),
  seedNorm({
    normId: 'norm_seed_tenwords_p5',
    sourceRef: 'Количество слов на 5-м предъявлении — 10 слов',
    methodId: 'ten_words',
    metric: 'p5',
    ageMin: 18,
    ageMax: 45,
    cellN: 500,
    statForm: 'mean_sd',
    mean: 10,
    sd: 3,
    higherIsWorse: false,
    dataCollectionYear: 2015,
    publicationYear: 2015,
  }),
];
